services:
  - type: web
    name: newspulse-api
    env: node
    region: singapore
    plan: starter
    buildCommand: npm ci
    startCommand: node app.js
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22
     services:


